services:
  http-server:
    build:
      context: ./http_server
      dockerfile: ./Dockerfile
    restart: on-failure
    ports: 
      - '8080:80'
  mariadb-database:
    
    image: mariadb
    ports:
      - '3306:3306'
    command: --max_connections=1000
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example_password
      MARIADB_USER : user
      MARIDB_PASSWORD : example_password
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  post-service:
    build:
      context: ./post-service
      dockerfile: ./Dockerfile
    restart: on-failure
    
  splitter:
    build:
      context: ./splitter
      dockerfile: ./Dockerfile
  auth-service:
    restart: on-failure
    depends_on:
      - mariadb-database
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
