services:
  http-server:
    build:
      context: ./http_server
      dockerfile: ./Dockerfile
    ports: 
      - '8080:80'
  mariadb-database:
    hostname: "127.0.0.1"
    
    image: mariadb
   # ports:
    #  - '3306:3306'
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example_password
      MARIADB_USER : user
      MARIDB_PASSWORD : example_password
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  splitter:
    build:
      context: ./splitter
      dockerfile: ./Dockerfile
    ports: 
      - '3035:3035'
  auth-service:
    restart: on-failure
    depends_on:
      - mariadb-database
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
