services:
  http-server:
    build:
      context: ./http_server
      dockerfile: ./Dockerfile
    restart: on-failure
    ports: 
      - '8080:80'
  mariadb-database:
    
    image: mariadb

    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example_password
      MARIADB_USER : user
      MARIDB_PASSWORD : example_password
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  splitter:
    build:
      context: ./splitter
      dockerfile: ./Dockerfile
    ports: 
      - '3035:3035'
  auth-service:
    restart: on-failure
    depends_on:
      - mariadb-database
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
