// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: splitter.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SplitterAuthClient is the client API for SplitterAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SplitterAuthClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type splitterAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewSplitterAuthClient(cc grpc.ClientConnInterface) SplitterAuthClient {
	return &splitterAuthClient{cc}
}

func (c *splitterAuthClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/splitterAuth/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *splitterAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/splitterAuth/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SplitterAuthServer is the server API for SplitterAuth service.
// All implementations must embed UnimplementedSplitterAuthServer
// for forward compatibility
type SplitterAuthServer interface {
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	mustEmbedUnimplementedSplitterAuthServer()
}

// UnimplementedSplitterAuthServer must be embedded to have forward compatible implementations.
type UnimplementedSplitterAuthServer struct {
}

func (UnimplementedSplitterAuthServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedSplitterAuthServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSplitterAuthServer) mustEmbedUnimplementedSplitterAuthServer() {}

// UnsafeSplitterAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SplitterAuthServer will
// result in compilation errors.
type UnsafeSplitterAuthServer interface {
	mustEmbedUnimplementedSplitterAuthServer()
}

func RegisterSplitterAuthServer(s grpc.ServiceRegistrar, srv SplitterAuthServer) {
	s.RegisterService(&SplitterAuth_ServiceDesc, srv)
}

func _SplitterAuth_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitterAuthServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/splitterAuth/register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitterAuthServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SplitterAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SplitterAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/splitterAuth/login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SplitterAuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SplitterAuth_ServiceDesc is the grpc.ServiceDesc for SplitterAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SplitterAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "splitterAuth",
	HandlerType: (*SplitterAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _SplitterAuth_Register_Handler,
		},
		{
			MethodName: "login",
			Handler:    _SplitterAuth_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "splitter.proto",
}
